### ISSUE TITLE
Couldn't read dependencies

### ISSUE THREAD

**Issue by jhernandezmaices** [swennemans/nodewebkit-reactjs#1]
Hi,

I can't install nodewebkit-reactjs.

```
$ npm install
npm ERR! install Couldn't read dependencies
npm ERR! Error: Invalid name: "Node-webkit and React.js"
npm ERR!     at ensureValidName (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:284:15)
npm ERR!     at Object.module.exports.fixNameField (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:199:5)
npm ERR!     at /usr/lib/nodejs/normalize-package-data/lib/normalize.js:29:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/usr/lib/nodejs/normalize-package-data/lib/normalize.js:28:15)
npm ERR!     at final (/usr/lib/nodejs/read-package-json/read-json.js:310:33)
npm ERR!     at then (/usr/lib/nodejs/read-package-json/read-json.js:124:33)
npm ERR!     at /usr/lib/nodejs/read-package-json/read-json.js:299:40
npm ERR!     at fs.js:268:14
npm ERR!     at /usr/lib/nodejs/graceful-fs/graceful-fs.js:103:5
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-45-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/jhernandez/Code/nodewebkit-reactjs
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jher
```

Any solution ?

**Comment by swennemans** [comment]
@jhernandezmaices the package.json name was invalid. I've adjusted it, it should work now. But, please be aware that this rep is pretty old. 
There have been a lot of updates in, nodewebkit (now NW.js) and React world.

**Comment by jhernandezmaices** [comment]
Yes, now is right !

@swennemans thank you.
